dataset: "Arabic"

path:
  corpus_path: "/kaggle/input/corpus-preprocess/Corpus_preprocess"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "/kaggle/input/corpus-preprocess/Corpus_preprocess/raw_data/Arabic"
  preprocessed_path: "/kaggle/input/corpus-preprocess/Corpus_preprocess/preprocessed_data/Arabic"
  stats_path: "/kaggle/input/corpus-preprocess/Corpus_preprocess/preprocessed_data/Arabic"
  

preprocessing:
  val_size: 14
  text:
    text_cleaners: []
    language: "ar"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
