dataset: "Arabic"

path:
<<<<<<< HEAD
  corpus_path: "/content/drive/MyDrive/ClArTTS"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "/content/drive/MyDrive/ClArTTS_preprocessed/raw_data/Arabic"
  preprocessed_path: "/content/drive/MyDrive/ClArTTS_preprocessed/preprocessed_data/Arabic"
  stats_path: "/content/drive/MyDrive/ClArTTS_preprocessed/preprocessed_data/Arabic"
=======
  corpus_path: "/content/drive/MyDrive/arabic-speech-corpus"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "/content/drive/MyDrive/Corpus_preprocess/raw_data/Arabic"
  preprocessed_path: "/content/drive/MyDrive/Corpus_preprocess/preprocessed_data/Arabic"
  stats_path: "/content/drive/MyDrive/Corpus_preprocess/preprocessed_data/Arabic"
>>>>>>> 2ed4de2f71e675ba6484ccf6de3d6ea789722bb7

preprocessing:
  val_size: 14
  text:
    text_cleaners: []
    language: "ar"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
